config/routes.rb
Rails.application.routes.draw do
  
  resources :gossips, only:[:edit, :update, :new, :index, :create, :destroy]
  root 'gossips#index'
  devise_for :corsaires
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsaire.rb
class Corsaire < ApplicationRecord

  attr_accessor :sign_up_code
  validates :sign_up_code,
    on: :create,
    presence: true,
    inclusion: { in: ["GOSSIP17"] }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gossips
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :corsaire
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:anonymous_username,:sign_up_code])
  end

  private
    # Before filters
    # Confirms a logged-in Corsaire.
    def logged_in_corsaire
      unless corsaire_signed_in?
        #store_location
        flash[:danger] = "Please log in."
        redirect_to new_corsaire_session_path
      end
    end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :logged_in_corsaire, only: [:new, :create, :edit, :update, :destroy]
  before_action :current_corsaire, only: [:destroy]
  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.corsaire = current_corsaire
    if @gossip.save  
      flash[:success] = "You've just sent a gossip, congrats!"
      redirect_to gossips_path
    else
      flash[:danger] = "Can't take your gossip, sorry..."
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy
    Gossip.find(params[:id]).destroy
    redirect_to root_path
  end

  def index
    @gossips = Gossip.all
  end


  private
    def gossip_params
      params.require(:gossip).permit(:content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_corsaire?(corsaire)
    corsaire ==current_corsaire
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>
<p>Find me in app/views/gossips/edit.html.erb</p>

app/views/gossips/index.html.erb
<h1>Gossips</h1>
<% if corsaire_signed_in? %>
  <ul>
    <% @gossips.each do |gossip| %>

    <li id="micropost-<%= gossip.id %>"> 
      <span class="content"><%= gossip.content %></span>
      <span class="user">, by <%= gossip.corsaire.anonymous_username %></span>
      <span class="timestamp">
        Posted <%= time_ago_in_words(gossip.created_at) %> ago.
        <% if current_corsaire?(gossip.corsaire) %>
          <%= link_to "delete", gossip, method: :delete %>
        <%end%>
      </span>
    </li>

    <% end %>
  </ul>
<% else %>
  <p>Please <%= link_to "Sign in", new_corsaire_session_path %> or <%= link_to 'Sign up', new_corsaire_registration_path %> if not yet done to see the gossips!</p>
<% end %>

app/views/gossips/new.html.erb
<h1>Gossip creation</h1>
<div class=“row”>
 <div class=“col-md-6 col-md-offset-3">
    <%= form_for(@gossip) do |f| %>
      <%= f.label :content %>
      <%= f.text_field :content, size: 150 %> 
      <%= f.submit "Submit your gossip" %>
    <% end %>
  </div>
</div>

app/views/gossips/show.html.erb
<h1>Gossips#show</h1>
<p>Find me in app/views/gossips/show.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "The Gossip Project", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if corsaire_signed_in? %>
          <li><%= link_to "Sign Out", destroy_corsaire_session_path, method: :delete %></li>
          <li> <%= link_to "New gossip", new_gossip_path %></li>
          <li><%= link_to "Edit Account", edit_corsaire_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_corsaire_registration_path %></li>
          <li><%= link_to "Sign In", new_corsaire_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>